services:
  optitrack:
    image: jeguzzi/optitrack_ros_py:lyrical
    build:
      context: ../../..
      dockerfile: optitrack_ros_py/docker/lyrical/Dockerfile
    command: ros2 launch optitrack_ros_py single.launch name:=test