version: '3'
services:
  optitrack:
    image: jeguzzi/optitrack_ros_py:humble
    build:
      context: .
      dockerfile: Dockerfile
    command: ros2 launch optitrack_ros_py single.launch name:=test